#!/usr/bin/env bash
# regenerate-continuation-exports.sh — Regenerate docs/CONTINUATION.html and
# docs/CONTINUATION.pdf from docs/CONTINUATION.md via pandoc + weasyprint.
#
# Purpose: docs/CONTINUATION.md is NOT a registered docs_chain context (only
# codegraph-status and features-status are — see .docs_chain/contexts/) so
# `docs_chain sync --all` never regenerates its exports. It IS technically in
# scope for scripts/generate_markdown_exports.sh (that generic sweep walks all
# of docs/**/*.md), but that script was flagged (BOB task #80) for corrupting
# docs_chain-managed docx baselines elsewhere under docs/ because its
# mtime-gated pandoc pass is docs_chain-unaware. Running it globally just to
# fix CONTINUATION's two stale exports risks re-triggering that class of
# regression against unrelated docs_chain-tracked files also living under
# docs/. This script instead does a SURGICAL, single-target regeneration:
# it touches ONLY docs/CONTINUATION.html and docs/CONTINUATION.pdf, using the
# exact same pandoc/weasyprint invocation shape as
# scripts/generate_markdown_exports.sh, so output stays consistent with every
# other exported doc in the project without touching that script or any
# docs_chain-managed file.
#
# Usage:
#   bash scripts/regenerate-continuation-exports.sh
#
# Inputs:
#   docs/CONTINUATION.md (must exist; this script never writes to it — it is
#   authoritative per §12.10 and is never regenerated by this script)
#
# Outputs:
#   docs/CONTINUATION.html — pandoc markdown -> html5
#   docs/CONTINUATION.pdf  — weasyprint render of the just-produced HTML
#
# Side-effects: none beyond writing the two files above. No git operations.
#
# Dependencies: pandoc (required — hard-fails if absent per §11.4.3, since an
# export gate failure with no tool is a hard blocker, not a soft skip);
# weasyprint (optional — SKIPs the PDF step with an honest §11.4.3 reason if
# absent, exactly like generate_markdown_exports.sh's own weasyprint
# detection).
#
# Idempotent: always regenerates on invocation (unconditional — this is a
# deliberately-invoked single-target regen, not a sweep with its own
# mtime-gating; callers wanting mtime-gated behavior should check
# docs/CONTINUATION.md's mtime against the exports themselves before calling).
#
# Cross-references: docs/scripts/regenerate-continuation-exports.md (external
# user guide per §11.4.18); scripts/generate_markdown_exports.sh (the generic
# sweep this script deliberately does NOT invoke, for the reason above);
# scripts/pre_build_verification.sh invariant 16 (CM-MARKDOWN-EXPORT-SYNC,
# the gate this script exists to satisfy for docs/CONTINUATION.md).
#
# Constitution: §11.4.65 (Universal Markdown export mandate), §11.4.12
# (auto-generated docs sync), §11.4.18 (script documentation mandate), §12.10
# (CONTINUATION.md maintenance — this script keeps its exports, never its
# content, in sync).

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MD="${PROJECT_ROOT}/docs/CONTINUATION.md"
HTML="${PROJECT_ROOT}/docs/CONTINUATION.html"
PDF="${PROJECT_ROOT}/docs/CONTINUATION.pdf"

if [[ ! -f "${MD}" ]]; then
    echo "FATAL: ${MD} not found — cannot regenerate exports for a source that does not exist" >&2
    exit 1
fi

if ! command -v pandoc &>/dev/null; then
    echo "FATAL: pandoc not available — cannot regenerate ${HTML}" >&2
    echo "This is a hard failure (not a §11.4.3 SKIP): CM-MARKDOWN-EXPORT-SYNC requires this export to exist and pandoc is the only converter this script supports for CONTINUATION.md." >&2
    exit 1
fi

echo "[regen] docs/CONTINUATION.md -> docs/CONTINUATION.html"
pandoc -f markdown -t html5 -o "${HTML}" "${MD}" --metadata title="CONTINUATION"
echo "[regen] wrote ${HTML}"

if command -v weasyprint &>/dev/null && python3 -c "from weasyprint import HTML" &>/dev/null 2>&1; then
    echo "[regen] docs/CONTINUATION.html -> docs/CONTINUATION.pdf"
    weasyprint "${HTML}" "${PDF}"
    echo "[regen] wrote ${PDF}"
else
    echo "SKIP: weasyprint not available — ${PDF} not regenerated (§11.4.3 honest skip)" >&2
fi

echo "[regen] done."
exit 0
