#!/usr/bin/env bash
# test_export_staleness_spaced_path_generator.sh — BOB-249 review I1 end-to-end:
# a locally edited .md whose path contains a SPACE must have its twins
# regenerated by scripts/generate_markdown_exports.sh (explicit-scope mode), and
# an UNEDITED spaced-path source must NOT be rewritten. Sandbox git repo only.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GEN="$(cd "${HERE}/../.." && pwd)/scripts/generate_markdown_exports.sh"
PASS=0; FAIL=0
pass(){ echo "PASS: $*"; PASS=$((PASS+1)); }
fail(){ echo "FAIL: $*"; FAIL=$((FAIL+1)); }
command -v pandoc >/dev/null || { echo "SKIP: pandoc absent"; exit 0; }
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
R="$TMP/repo"; mkdir -p "$R/docs/sp ace"
G(){ git -C "$R" -c user.name=t -c user.email=t@t -c commit.gpgsign=false "$@"; }
G init -q
M="$R/docs/sp ace/Guide One.md"
printf '# T\n\noriginal text\n' > "$M"
GOMAXPROCS=2 nice -n 19 bash "$GEN" "$M" >/dev/null 2>&1
G add -A >/dev/null; G commit -qm base
H="$R/docs/sp ace/Guide One.html"
[[ -f "$H" ]] || { fail "setup: html not generated"; exit 1; }
# control: unedited, md newer than twins by mtime only -> nothing rewritten
touch -d '2020-01-01' "$H" "${H%.html}.docx"; touch -d '2021-01-01' "$M"
b1="$(stat -c %Y "$H")"
GOMAXPROCS=2 nice -n 19 bash "$GEN" "$M" >/dev/null 2>&1
[[ "$(stat -c %Y "$H")" == "$b1" ]] && pass "unedited spaced-path source not regenerated" || fail "unedited spaced-path source spuriously regenerated"
# edit locally
printf '# T\n\nEDITED-NEEDLE text\n' > "$M"
GOMAXPROCS=2 nice -n 19 bash "$GEN" "$M" >/dev/null 2>&1
grep -q 'EDITED-NEEDLE' "$H" && pass "edited spaced-path source: html regenerated (needle present)" || fail "edited spaced-path source: html NOT regenerated"
unzip -p "${H%.html}.docx" word/document.xml 2>/dev/null | grep -q 'EDITED-NEEDLE' && pass "docx regenerated (needle present)" || fail "docx NOT regenerated"
echo "RESULT: $PASS passed, $FAIL failed"; [ "$FAIL" -eq 0 ]
